### ISSUE TITLE
Invalid/expired session ID

### ISSUE THREAD

**Issue by gabrielreynira** [lavovaLampa/patreon-scraper#2]
This is most likely me being terrible at using this rather than anything else, but I'm having an issue when trying to use ts-node index.ts -s --session id, where it returns 'Invalid/expired session ID', and I don't know why or how to fix it? I'd love to figure this out somehow, this program is exactly what I need!

**Comment by lavovaLampa** [comment]
Hey, you should only use one of the (-s/--sessionId) switches. E.g.:
`./index.ts -s <your_session_id>`, or equivalently `./index.ts --sessionId <your_session_id>`

I should probably state that explicitly though :)

**Comment by gabrielreynira** [comment]
Yeah, that's it, thanks!
